export { default as Navbar } from './navbar/Navbar'
export { default as Coding_buddy } from './coding_buddy/Coding_buddy'
export { default as About } from './about/About'
export { default as Me } from './me/Me'
export { default as Contribute } from './contribute/Contribute'
export { default as Footer } from './footer/Footer'
export { default as Search_page } from './search_page/Search_page'